name: Laravel
on:
  push:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  DB_HOST: mysql
  DB_DATABASE: example_app
  DB_USERNAME: sail
  DB_PASSWORD: password
  MAIL_FROM_ADDRESS: info@example.com

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: "mysql/mysql-server:8.0"
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: "example_app"
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
      - name: Copy .env
        run: cp .env.example .env.testing
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate --env testing
      - name: Run migrations
        run: php artisan migrate --env testing
      - name: Set hostname
        run: sudo echo "127.0.0.1 mysql.test"  | sudo tee -a /etc/hosts
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php -d memory_limit=-1 vendor/bin/phpunit --configuration phpunit.xml
